
server:
  port: 8888
  
spring:
  cloud:
    config:
      server:
        encrypt:
            enabled: false
        git:
          uri: https://github.com/ykaique/microservice-repo/
          search-paths: fornecedor, loja, transportador